# Generated by Django 4.2.1 on 2023-05-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PythonSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("task", models.TextField(blank=True, null=True)),
                ("code", models.TextField(blank=True, null=True)),
                ("accepted", models.BooleanField(default=False)),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "time_complexity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("aod", models.TextField(blank=True, null=True)),
                ("edited", models.DateTimeField(auto_now_add=True)),
                ("created", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
